const GET_MARKERS = 'GET_MARKERS';
const CREATE_MARKER = 'CREATE_MARKER';
const JOIN_ROOM = 'JOIN_ROOM';
const GET_ROOMS = 'GET_ROOMS';
const UPDATE_MARKER = 'UPDATE_MARKER';
const GET_PARTNERS = 'GET_PARTNERS';

export default {
	GET_MARKERS,
	CREATE_MARKER,
	JOIN_ROOM,
	GET_ROOMS,
	UPDATE_MARKER,
	GET_PARTNERS
};